CREATE TABLE "app_configs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_configs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"key" varchar(32) NOT NULL,
	"value" varchar(255) NOT NULL,
	"description" varchar(255),
	"version" varchar(32) NOT NULL,
	"value_type" varchar(32) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
DROP TABLE "users";
